version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-lambda-joshua"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-e1vfpglebxnm"
s3_prefix = "test-lambda-joshua"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
